name: Unity Build
on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        unity_version: ["6000.0.53f1"]
        include:
          - os: ubuntu-latest
            target_platform: StandaloneLinux64
            build_name: Xaloc_Tanks_Linux
          - os: windows-latest
            target_platform: StandaloneWindows64
            build_name: Xaloc_Tanks_Windows
          - os: macos-latest
            target_platform: StandaloneOSX
            build_name: Xaloc_Tanks_macOS

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        lfs: true

    - name: Cache Unity modules
      uses: actions/cache@v4
      id: module-cache
      with:
        path: |
          "${{ runner.tempDir }}/modules"
          "${{ runner.tempDir }}/modules.json"
        key: modules-${{ matrix.target_platform }}-${{ matrix.unity_version }}

    - name: Build Unity project
      uses: game-ci/unity-builder@v4
      with:
        targetPlatform: ${{ matrix.target_platform }}
        projectPath: .
        buildName: ${{ matrix.build_name }}
        buildsPath: Builds/${{ matrix.build_name }}
        unityVersion: ${{ matrix.unity_version }}

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.build_name }} Build
        path: Builds/${{ matrix.build_name }}
        retention-days: 5